dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
networks:
  rinkeby:
    verify: True
  kovan:
    verify: True
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env